---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-oidc
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: "kubernetes/namespaces/base/management-system/config/oidc"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
