swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "team-alpha.endpoints.anz-next-demo-23.cloud.goog"
x-google-endpoints:
- name: "team-alpha.endpoints.anz-next-demo-23.cloud.goog"
  target: "34.149.140.232"
