---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: whereami-ingress
  namespace: demo
  annotations:
    # Hardcoded IP address for the ingress GCLB
    networking.gke.io/static-ip: 34.120.31.190
    networking.gke.io/pre-shared-certs: "whereamicert"
spec:
  template:
    spec:
      backend:
        serviceName: whereami-mcs
        servicePort: 8080
