---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: whereami-mcs
  namespace: demo
spec:
  template:
    spec:
      selector:
        app: whereami
      ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
