kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: bravo-team-external-http
  namespace: team-bravo-tenant
spec:
  gatewayClassName: gke-l7-global-external-managed-mc
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            bravo-team-shared-gateway-access: "true"
